# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - "*"


pool:
  vmImage: 'ubuntu-latest'


steps:
- checkout: self

- script: make init
  displayName: 'build compile environment'

- script: make sync
  displayName: 'sync dependencies'

- script: make gym
  displayName: 'build gym'

- script: mkdir -p traces && target/webrtc_test
  displayName: 'execute gym'
